//account
export const UPDATE_PHILLANDS_PROFILE = 'UPDATE_PHILLANDS_PROFILE'
//modals
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL'
export const TOGGLE_FEEDBACK_MODAL = 'TOGGLE_FEEDBACK_MODAL'
//search
export const UPDATE_PHILLANDS_SEARCH = 'UPDATE_PHILLANDS_SEARCH'
